version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: enessermaxhaj/backend:latest
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    image: enessermaxhaj/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend